version: "3.9"

services:
  navbar:
    container_name: navbar-app
    restart: always
    build:
      context: ./navbar
      dockerfile: Dockerfile.dev
    ports:
      - "9000:3000"
    volumes:
      - ./navbar/:/nav-app/
      - /nav-app/node_modules
  home:
    container_name: home-app
    build:
      context: ./home
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    restart: always
    volumes:
      - ./home/:/home-app/
      - /home-app/node_modules
